### ISSUE TITLE
how to add touch for jCarousel?

### ISSUE THREAD

**Issue by happyduong** [felquis/jCarouselSwipe#1]
I using jCarousel. And now i need touch features for jCarousel. you can help me adding touch more detail?
thank.
best regard.

**Comment by vomc** [comment]
just curious is this abandonware? I installed it with all the dependencies but not working on my phone... it this real or a joke project?

**Comment by SUKHI-AATMA** [comment]
@felquis 
I am not able to make this plugin work. A working demo would be awesome. Posting my code please tell me where i am lacking.

[jcarousel-touch.txt](https://github.com/felquis/jCarouselSwipe/files/489486/jcarousel-touch.txt)

**Comment by felquis** [comment]
@vomc this is abandonware. I didn't notice your notification at the time. Hope the source gave u some insight 4 yr ago😆
